name: Build Native Addon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install build tools (Windows)
      if: runner.os == 'Windows'
      run: |
        npm install --global windows-build-tools
        npm config set msvs_version 2019
    
    - name: Install build tools (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    
    - name: Build native addon
      run: npm run build
    
    - name: Test addon
      run: npm test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: addon-${{ matrix.os }}-node${{ matrix.node-version }}
        path: |
          build/Release/*.node
          build/Release/*.dll
          build/Release/*.so
          build/Release/*.dylib
        retention-days: 30

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create release archive
      run: |
        cd artifacts
        for dir in */; do
          cd "$dir"
          zip -r "../$(basename "$dir").zip" .
          cd ..
        done
    
    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.zip
      env:
        token: ${{ secrets.GITHUB_TOKEN }}